apiVersion: v2
name: k8s-lb-controller
description: A lightweight Kubernetes LoadBalancer controller with local HAProxy and optional standalone dataplane API rollout modes.
type: application
version: 0.1.0
appVersion: "0.1.0"
home: https://github.com/voronkov44/k8s-lb-controller
sources:
  - https://github.com/voronkov44/k8s-lb-controller
keywords:
  - kubernetes
  - controller
  - loadbalancer
  - haproxy
  - networking
maintainers:
  - name: voronkov44
annotations:
  org.opencontainers.image.licenses: Apache-2.0
