{{- if .Values.metrics.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-lb-controller.fullname" . }}-metrics
  labels:
    {{- include "k8s-lb-controller.labels" . | nindent 4 }}
    {{- with .Values.metrics.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.metrics.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  selector:
    {{- include "k8s-lb-controller.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.metrics.port }}
      protocol: TCP
      targetPort: metrics
{{- end }}
